### PR TITLE
showcase-light version

### PR DESCRIPTION
**Pull request by BogdanScherban**
Added Showcase-light version.

### CODE REVIEW

**Comment by BogdanScherban** [comment]
Slowcase-light version include following plugins:
- problems
- allergies;
- contacts;
- medications;
- vaccinations;
- top three things;

Patient Summary has two modes: roll and table.

Home page is patients list with searches (simple search, advanced and clinical).

Also this version has business-intelligence page.

**Comment by tony-shannon** [comment]
thanks Bogdan @BogdanScherban , I think we can remove the Business Intelligence view and the Roll view please, to keep it very simple
Can you also add in Vitals signs and remove Top Three Things

Can you also explain the directory structure, is this a new project within Lerna, with a build folder?
thanks

**Comment by BogdanScherban** [comment]
1) Removed Business intelligence;
2) Removed roll view for Summary
3) Vitals instead of TopThreeThings

Files structure:
``` 
|-- packages 
|------ pulsetile-react-admin 
|-- projects 
|------ helm 
|------ london 
...
...
|------ showcase 
|------ showcase-light /           // Showcase-light version
|------------ build                // Build directory
|------------ public               // Fonts, favicon, icons and index.html
|------------ src /
|----------------- custom          // Topbar, Sidebar, styles, version configuration
|----------------- images          // Version images
|----------------- App.js          // Pulsetile-react-admin importing and properties adding to it
|----------------- index.js        // root file
|------------ package.json         // settings of package
|------------ README.md            // description
|------ slaintecare 
```

**Comment by tony-shannon** [comment]
many thanks Bogdan, will merge now

**Pull request merged**
